# Shopify App Configuration
name = "peeq"
client_id = "8750cb98a2fa7d3e954417d7c7ed0790"
application_url = "https://store-app.peeq.co.in"
embedded = false

[auth]
redirect_urls = [
  "https://store-app.peeq.co.in/auth/callback"
]

[webhooks]
api_version = "2024-04"

# Mandatory compliance webhooks
[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact", 
  "shop/redact"
]
uri = "https://store-app.peeq.co.in/webhooks"
